### ISSUE TITLE
你好，我有一些疑问想问问

### ISSUE THREAD

**Issue by lizy0329** [airplayx/eoLinker#1]
1. eolinker_os_5.0 是你基于 eolinker_os_4.0 修改的，并不是官方的是吗？
2. 这个开源版本对于账号的管理完善吗？我希望为  eolinker_os_5.0 添加对 ldap 的支持
3. 可以有 docker 版本？

**Comment by airplayx** [comment]
您好，项目都是从之前官方代码拉下来的，5版本也是。
改动都是依照自己发现的错误进行的改动。
这个项目没有前端工程的，都是打包好的文件。你想改动的话估计有点麻烦，或者自己在翻翻其他人的代码。当然php可以自己改动。
目前没有docker的打算。

**Comment by lizy0329** [comment]
> 您好，项目都是从之前官方代码拉下来的，5版本也是。
> 改动都是依照自己发现的错误进行的改动。
> 这个项目没有前端工程的，都是打包好的文件。你想改动的话估计有点麻烦，或者自己在翻翻其他人的代码。当然php可以自己改动。
> 目前没有docker的打算。

谢谢你的回复，我已经将 eolinker_os_4.0 部署了测试看看，很多功能都不如 yapi，我打算用回 yapi

**Comment by airplayx** [comment]
好的
